This is a free to use website that allows you to use your web browser's built in speech to text to control the users custom built audio library. I will be releasing videos on how to use every feature in the program eventually (hopefully) but for now please reference the guidebook.

For those of you that care, please know that 99.99% of the code was generated by Gemini 2.5 ai.

The reality is that if I wanted to build something like this it would have taken me years to learn how to do it and I have to many other responsibilities and hobbies to put in that much work.

All the concepts and ideas for how the program runs and operates were designed by me. I have been working on and developing this program project for over a year. I do not know how to code, 
please forgive me if the program is ineffecient or not built well. 

To be honest I never expected the ai to be able to take me this far in development. 
But here we are a year later with more features and systems than I ever thought possible.

I dont consider myself a programmer or developer, more just a idea man/manager/QA control guy. That being said I have definitly put 100+ hrs into working on this even with the heavy use of ai.

This sparked out of an idea I had where I could be narrating in my D&D campaign and sound effects and music would play automatically without me having to fumble around or look at my computer. 

I hope you are able to find some use or enjoyment out of this program :)

ps. if you have any ideas or want to help with its development/imporvement let me know.
